### PR TITLE
Pet

### PR DESCRIPTION
**Pull request by Jonathan57500**

### CODE REVIEW

**Comment by determinated** [comment]
The biggest problem of this server is the skill motions idk how to fix, if somebody could do it would be very nice.

**Comment by determinated** [comment]
Anybody still working on it?

**Comment by Jonathan57500** [comment]
Yes, but as it is not affected to any real project there is no real work on it :)

**Comment by determinated** [comment]
I was trying to put the "temporary spawn" on source but i couldnt. This is used to set npcs respawn times like for fenris quest. Some npcs appear just from 8am to 10am... I was trying to fix it but unfortunately i couldnt. If you work on it with me i can help you to make it a retail server. I'm not very good at src i know how to fix things on data. If you want to work together let me know bud.

**Comment by Jonathan57500** [comment]
It would be cool, but without a concrete project I'm afraid I will not allow a lot of time on it :(

**Comment by determinated** [comment]
I would open a public private server if we can make some corrections in this server. If you want this we can find a country and open a retail server there. This src is very cool

**Comment by determinated** [comment]
I want to work on it to make a private server in a near future

**Comment by Jonathan57500** [comment]
This emu is working, you can make a great server with a minimum of uncomfortable things. To make a new 2.7 Aion server, you don't only need an emulator in 2019, you need a real project, an ambitious project, with a complete staff and a new vision of what this game should be.

**Comment by determinated** [comment]
Unfortunately, i'll be working on this emu and send you the fixes when i have done. And yes this emu is great. If i find a problem that i cant fix i'll be posting here so maybe i can have some help.

**Comment by Jonathan57500** [comment]
Yes of course if you are working on the emu I'll help :)

**Comment by determinated** [comment]
Thx alot bud.

**Comment by determinated** [comment]
Well for now i'm trying to put this to work.


		<spawn npc_id="210590" respawn_time="1800">
		    <temporary_spawn spawn_time="21.*.*" despawn_time="4.*.*"/>
			<spot x="556.9371" y="2242.813" z="247.5" h="115"/>
		</spawn>
(test npc)

i implemented this on source and compiled fine.

When i execute the GS i get this Error at [line=858, column=14127803]: unexpected element (uri:"", local:"temporary_spawn"). Expected elements are <{}spot>
 
and i've add the temporary_spawn in spawns.xsd file. So now i'm stuck.

**Comment by Jonathan57500** [comment]
This is probably not the best place for support, but try in xsd file something like (replace Spawn and SpawnSpotTemplate with this):
```
<xs:complexType name="Spawn">
  <xs:sequence>
    <xs:element name="spot" type="SpawnSpotTemplate" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="temporary_spawn" type="TemporarySpawnTemplate" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="npc_id" type="xs:int"/>
  <xs:attribute name="pool" type="xs:int" use="optional"/>
  <xs:attribute name="spawn_time" type="SpawnTimeType" use="optional" default="ALL"/>
  <xs:attribute name="respawn_time" type="xs:int"/>
  <xs:attribute name="handler" type="SpawnHandlerType"/>
  <xs:attribute name="custom" type="xs:boolean" use="optional" default="false"/>
</xs:complexType>
<xs:complexType name="SpawnSpotTemplate">
  <xs:attribute name="x" type="xs:float"/>
  <xs:attribute name="y" type="xs:float"/>
  <xs:attribute name="z" type="xs:float"/>
  <xs:attribute name="h" type="HeadingType" use="optional" default="0"/>
  <xs:attribute name="static_id" type="xs:int" use="optional" default="0"/>
  <xs:attribute name="random_walk" type="xs:int" use="optional" default="0"/>
  <xs:attribute name="walker_id" type="xs:string"/>
  <xs:attribute name="walker_index" type="xs:int" use="optional" default="0"/>
  <xs:attribute name="fly" type="xs:int" use="optional" default="0"/>
  <xs:attribute name="anchor" type="xs:string"/>
  <xs:attribute name="state" type="xs:int" use="optional" default="0"/>
</xs:complexType>
<xs:complexType name="TemporarySpawnTemplate">
  <xs:attribute name="x" type="xs:float"/>
  <xs:attribute name="y" type="xs:float"/>
  <xs:attribute name="z" type="xs:float"/>
  <xs:attribute name="h" type="HeadingType" use="optional" default="0"/>
  <xs:attribute name="static_id" type="xs:int" use="optional" default="0"/>
  <xs:attribute name="random_walk" type="xs:int" use="optional" default="0"/>
  <xs:attribute name="walker_id" type="xs:string"/>
  <xs:attribute name="walker_index" type="xs:int" use="optional" default="0"/>
  <xs:attribute name="fly" type="xs:int" use="optional" default="0"/>
  <xs:attribute name="anchor" type="xs:string"/>
  <xs:attribute name="state" type="xs:int" use="optional" default="0"/>
</xs:complexType>
```

**Comment by determinated** [comment]
Doesnt work.

Mine is like this: 

<xs:complexType name="Spawn">
		<xs:sequence>
		    <xs:element name="temporary_spawn" type="TemporarySpawn" minOccurs="0" maxOccurs="1"/>
			<xs:element name="spot" type="SpawnSpotTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="npc_id" type="xs:int"/>
		<xs:attribute name="pool" type="xs:int" use="optional"/>
		<xs:attribute name="spawn_time" type="SpawnTimeType" use="optional" default="ALL"/>
		<xs:attribute name="respawn_time" type="xs:int"/>
		<xs:attribute name="handler" type="SpawnHandlerType"/>
		<xs:attribute name="custom" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="SpawnSpotTemplate">
	<xs:sequence>
			<xs:element name="temporary_spawn" type="TemporarySpawn" minOccurs="0" maxOccurs="1"/>
			<xs:element name="model" type="SpawnModel" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="x" type="xs:float"/>
		<xs:attribute name="y" type="xs:float"/>
		<xs:attribute name="z" type="xs:float"/>
		<xs:attribute name="h" type="HeadingType" use="optional" default="0"/>
		<xs:attribute name="static_id" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="random_walk" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="walker_id" type="xs:string"/>
		<xs:attribute name="walker_index" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="fly" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="anchor" type="xs:string"/>
		<xs:attribute name="state" type="xs:int" use="optional" default="0"/>
	</xs:complexType>
	<xs:complexType name="SpawnModel">
		<xs:attribute name="tribe" type="TribeClass"/>
		<xs:attribute name="ai" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TemporarySpawn">
		<xs:attribute name="spawn_time" type="xs:string"/>
		<xs:attribute name="despawn_time" type="xs:string"/>
	</xs:complexType>

Do you have this implemented?

**Comment by determinated** [comment]
I have your skype if you want to talk there

**Pull request merged**
